threatresponse:
  image: threatresponse/threatresponse:latest
  privileged: true
  environment:
    - CASE_NUMBER=${CASE_NUMBER}
  ports:
    - "9999:9999"
  volumes:
    - .:/app
    - /tmp:/tmp
    - ./tmp:/app/tmp
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - redis
redis:
  image: redis
  ports:
    - "6379"
volatility:
  image: threatresponse/xterm.js
  volumes:
    - ./tmp/:/analysis
  ports:
    - "3000:3000"
